=== GLEIF-IT/w3c-crosswalk/tests/integration/_assets/vlei/schema/acdc/vrd-auth-schema.json
{
  "$id": "EFiYsVADHXcn1BZirDRH301Rm12301povihg5UMIYkfc",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Verifiable Reference Data (VRD) Authorization Credential",
  "description": "A VRD Authorization Credential issued by a Legal Entity to a QVI for the authorization of VRD credentials",
  "type": "object",
  "credentialType": "VRDAuthorizationCredential",
  "version": "1.0.0",
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "i": {
      "description": "LE Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "Schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "Attributes block SAID",
          "type": "string"
        },
        {
          "$id": "EAFCPtqS_ulIJ_9FL_R1kzj22j0lTUJEQniBWlX9l9-J",
          "description": "Attributes block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Attributes block SAID",
              "type": "string"
            },
            "i": {
              "description": "QVI Issuee AID",
              "type": "string"
            },
            "dt": {
              "description": "Issuance date time",
              "type": "string",
              "format": "date-time"
            },
            "AID": {
              "description": "AID of the Legal Entity of the VRD credential",
              "type": "string"
            },
            "DID": {
              "description": "DID of the Legal Entity",
              "type": "string"
            },
            "HeadquartersAddress": {
              "description": "Headquarters Address of the Legal Entity",
              "type": "string"
            },
            "LegalName": {
              "description": "Legal Name of the Legal Entity",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "i",
            "dt",
            "AID",
            "DID",
            "HeadquartersAddress",
            "LegalName"
          ]
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "Edges block SAID",
          "type": "string"
        },
        {
          "$id": "ECadfxrrTHs5-clF7_KYdF00qvgpYNH-B3vR7FkOg9ay",
          "description": "Edges block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Edges block SAID",
              "type": "string"
            },
            "le": {
              "description": "Chain to legal entity  credential",
              "type": "object",
              "properties": {
                "n": {
                  "description": "QVI Issuer credential SAID",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of required schema of the credential pointed to by this node",
                  "type": "string",
                  "const": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "le"
          ]
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "Rules block SAID",
          "type": "string"
        },
        {
          "$id": "EOJGdeB8bSOrLjE2SDpKpbY8Cn-kdGD1uS46FR5Jasp7",
          "description": "Rules block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Rules block SAID",
              "type": "string"
            },
            "usageDisclaimer": {
              "description": "Usage Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            },
            "issuanceDisclaimer": {
              "description": "Issuance Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            },
            "privacyDisclaimer": {
              "description": "Privacy Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "usageDisclaimer",
            "issuanceDisclaimer",
            "privacyDisclaimer"
          ]
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d",
    "e",
    "r"
  ]
}

=== GLEIF-IT/w3c-crosswalk/fixtures/vrd-auth-acdc.json
{
  "v": "ACDC10JSON00039a_",
  "d": "EPIRsje6P7Y2gzlRWz4oqGkrIzXPaVJIghyILx2SjtZc",
  "i": "EI_FTeKDGPKVxNzQT4A7I2KZ3WsL2b-xXTiR2Hioy5e8",
  "ri": "ECpRGfY0Kfvc-95DmKEyAxzDi6vQ5kizSO5xHWNEzMSK",
  "s": "EFiYsVADHXcn1BZirDRH301Rm12301povihg5UMIYkfc",
  "a": {
    "d": "EH8BN4CyoOHG-sP2hLy45JR1G1-0nS12TERhSg8dSQDu",
    "i": "EDiRogF6HnCw35tZ_lbGxGPQr527od6D_Uc6LNr6Xi_d",
    "dt": "2026-04-01T01:20:35.323209+00:00",
    "AID": "EI_FTeKDGPKVxNzQT4A7I2KZ3WsL2b-xXTiR2Hioy5e8",
    "DID": "did:webs:127.0.0.1%3A59160:dws:EI_FTeKDGPKVxNzQT4A7I2KZ3WsL2b-xXTiR2Hioy5e8",
    "HeadquartersAddress": "1 Market St, San Francisco, CA, US",
    "LegalName": "Example Legal Entity LLC"
  },
  "e": {
    "d": "EOrUdTDlRuy5DqshgBU60GNuWTvqihxYryULj9lP8XFE",
    "le": {
      "n": "EBugt3kU_mKtBxt3l75s5kkFE2i2ov3PzDnQpT3xYFjm",
      "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
    }
  },
  "r": {
    "d": "EAU19ld9joWluglfF24t9ZrS8Gjk4NlvB0_ct6Knz8qi",
    "usageDisclaimer": {
      "l": ""
    },
    "issuanceDisclaimer": {
      "l": ""
    },
    "privacyDisclaimer": {
      "l": ""
    }
  }
}
