=== GLEIF-IT/w3c-crosswalk/tests/integration/_assets/vlei/schema/acdc/vrd-schema.json
{
  "$id": "EAyv2DLocYxJlPrWAfYBuHWDpjCStdQBzNLg0-3qQ-KP",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Verifiable Reference Data (VRD) Credential",
  "description": "A VRD Credential issued by a Qualified vLEI Issuer to a LE",
  "type": "object",
  "credentialType": "VRDCredential",
  "version": "1.0.0",
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "i": {
      "description": "QVI Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "Schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "Attributes block SAID",
          "type": "string"
        },
        {
          "$id": "EIsncCzvBiY5g-JDJn2PreFbr1gANEepRTgK0U6BPhFE",
          "description": "Attributes block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Attributes block SAID",
              "type": "string"
            },
            "i": {
              "description": "QVI Issuee AID",
              "type": "string"
            },
            "dt": {
              "description": "Issuance date time",
              "type": "string",
              "format": "date-time"
            },
            "AID": {
              "description": "AID of the intended recipient of the VRD credential",
              "type": "string"
            },
            "DID": {
              "description": "DID of the intended recipient of the VCDM VRD credential",
              "type": "string"
            },
            "HeadquartersAddress": {
              "description": "Headquarters Address of the Legal Entity",
              "type": "string"
            },
            "LegalName": {
              "description": "LegalName of the Legal Entity",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "i",
            "dt",
            "AID",
            "DID",
            "HeadquartersAddress",
            "LegalName"
          ]
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "Edges block SAID",
          "type": "string"
        },
        {
          "$id": "EAtMAKVYGMKYbziGkL117tB9sL3yhbGwsKQJHet-jICc",
          "description": "Edges block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Edges block SAID",
              "type": "string"
            },
            "le": {
              "description": "Chain to Legal Entity vLEI credential",
              "type": "object",
              "properties": {
                "n": {
                  "description": "QVI Issuer credential SAID",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of required schema of the credential pointed to by this node",
                  "type": "string",
                  "const": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
                },
                "o": {
                  "description": "Edge operator for the Legal Entity chain",
                  "type": "string",
                  "const": "NI2I"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s",
                "o"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "le"
          ]
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "Rules block SAID",
          "type": "string"
        },
        {
          "$id": "EOJGdeB8bSOrLjE2SDpKpbY8Cn-kdGD1uS46FR5Jasp7",
          "description": "Rules block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Rules block SAID",
              "type": "string"
            },
            "usageDisclaimer": {
              "description": "Usage Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            },
            "issuanceDisclaimer": {
              "description": "Issuance Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            },
            "privacyDisclaimer": {
              "description": "Privacy Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": ""
                }
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "usageDisclaimer",
            "issuanceDisclaimer",
            "privacyDisclaimer"
          ]
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d",
    "e",
    "r"
  ]
}

=== GLEIF-IT/w3c-crosswalk/fixtures/vrd-acdc.json
{
  "v": "ACDC10JSON0003a5_",
  "d": "EILmWT5X9VkXbXY835ZJ9-kglSy-LPiKMEh_35cTg9P8",
  "i": "EDiRogF6HnCw35tZ_lbGxGPQr527od6D_Uc6LNr6Xi_d",
  "ri": "ENc9qcKyy9PvEsfTlPAEQfmm_rhxWuk6rA3D2w7AIK0V",
  "s": "EAyv2DLocYxJlPrWAfYBuHWDpjCStdQBzNLg0-3qQ-KP",
  "a": {
    "d": "EOVTd8qIS73KKKG5cZFBlIRYE6EqFpftoxTrfJYesM96",
    "i": "EI_FTeKDGPKVxNzQT4A7I2KZ3WsL2b-xXTiR2Hioy5e8",
    "dt": "2026-04-01T01:20:40.322388+00:00",
    "AID": "EI_FTeKDGPKVxNzQT4A7I2KZ3WsL2b-xXTiR2Hioy5e8",
    "DID": "did:webs:127.0.0.1%3A59160:dws:EDiRogF6HnCw35tZ_lbGxGPQr527od6D_Uc6LNr6Xi_d",
    "HeadquartersAddress": "1 Market St, San Francisco, CA, US",
    "LegalName": "Example Legal Entity LLC"
  },
  "e": {
    "d": "EHavX6lYNelLVAQHYaE088ukQFXuaZn-vyOnOFA_TXC_",
    "le": {
      "n": "EBugt3kU_mKtBxt3l75s5kkFE2i2ov3PzDnQpT3xYFjm",
      "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY",
      "o": "NI2I"
    }
  },
  "r": {
    "d": "EAU19ld9joWluglfF24t9ZrS8Gjk4NlvB0_ct6Knz8qi",
    "usageDisclaimer": {
      "l": ""
    },
    "issuanceDisclaimer": {
      "l": ""
    },
    "privacyDisclaimer": {
      "l": ""
    }
  }
}
